import {
  Operator,
  FeaturedTour,
  Tour,
  TourCategory,
  TransferRoute,
  Vehicle,
  Review,
  FaqItem,
} from './types';

export const OPERATOR: Operator = {
  name: 'Ibrahim',
  businessName: 'Ibrahim Tours Zanzibar',
  tagline: 'Your Trusted Guide to Paradise Island',
  experience: '10+ years',
  languages: ['English', 'Swahili', 'Italian'],
  phone: '+255700000000',
  whatsapp: '255700000000',
  email: 'info@ibrahimtours.co.tz',
  location: 'Stone Town, Zanzibar, Tanzania',
  trustPoints: [
    'Local licensed guide & native islander',
    '10+ years of 5-star experience',
    'Fluent in English, Swahili & Italian',
    'Direct instant WhatsApp booking & fast support',
    'Transparent pricing with zero hidden fees',
  ],
};

export const TOUR_CATEGORIES: TourCategory[] = [
  'Sea & Water',
  'City & Cultural',
  'Nature & Wildlife',
  'Island Experiences',
  'Beach & Island',
  'Full Day Combos',
];

// Homepage marketing cards. Each `slug` MUST resolve to an entry in ALL_TOURS below,
// otherwise the "Book Now" CTA and the footer tour links 404.
export const FEATURED_PACKAGES: FeaturedTour[] = [
  {
    id: 'feat-1',
    title: 'Mnemba Island',
    price: 160,
    category: 'Sea & Water',
    tagline: 'Snorkeling & swim with dolphins',
    duration: 'Full Day',
    slug: 'mnemba-island',
    image: '/images/tours/Mnemba/Mnemba-Island-4.jpg.jpeg',
  },
  {
    id: 'feat-2',
    title: 'Stone Town & Prison Island',
    price: 180,
    category: 'City & Cultural',
    tagline: 'Historic walk & giant tortoises',
    duration: 'Full Day',
    slug: 'town-full-day-combo',
    image: '/images/tours/Stonetown/ZOM_0097.JPG-300kb.jpg',
  },
  {
    id: 'feat-3',
    title: 'Spice Farm & Cooking Class',
    price: 190,
    category: 'City & Cultural',
    tagline: 'Spice farm + local cooking',
    duration: 'Full Day',
    slug: 'village-tour-cooking-class',
    image: '/images/tours/Village/Look-like-locals.jpg.jpeg',
  },
  {
    id: 'feat-4',
    title: 'Safari Blue',
    price: 215,
    category: 'Sea & Water',
    tagline: 'Full-day sea adventure + seafood lunch',
    duration: 'Full Day',
    slug: 'safari-blue',
    image: '/images/tours/Safariblue/the-original-safari-blue.jpg.jpeg',
  },
  {
    id: 'feat-5',
    title: 'Zanzibar Wildlife: Jozani Forest & Mtende Beach',
    price: 180,
    category: 'Nature & Wildlife',
    tagline: 'Red colobus monkeys & beach',
    duration: 'Full Day',
    slug: 'jozani-forest',
    image: '/images/tours/Jozani/6803148a-2b22-4f22-be2f-0825a2159110.jpg.jpeg',
  },
  {
    id: 'feat-6',
    title: 'Nakupenda Sandbank & Prison Island',
    price: 225,
    category: 'Sea & Water',
    tagline: 'White sandbank + tortoises',
    duration: 'Full Day',
    slug: 'nakupenda-sandbank',
    image: '/images/tours/Nakupenda/Nakupenda-Island-Zan-The-Level-2.jpg.jpeg',
  },
  {
    id: 'feat-7',
    title: 'The Rock Restaurant & Michamvi Beach',
    price: 150,
    category: 'Island Experiences',
    tagline: 'Iconic ocean dining & beach',
    duration: 'Half Day',
    slug: 'the-rock-restaurant',
    image: '/images/tours/Rock_Restaurant/The-rock-zanzibar-aerial-view.webp',
  },
  {
    id: 'feat-8',
    title: 'Zanzibar Northern Beach',
    price: 180,
    category: 'Beach & Island',
    tagline: 'Nungwi & Kendwa beaches',
    duration: 'Full Day',
    slug: 'north-full-day-combo',
    image: '/images/tours/Sunset/Zanzibar_Dhow_Sunset_Cruise_03.jpg.jpeg',
  },
];

export const ALL_TOURS: Tour[] = [
  {
    id: 'tour-1',
    title: 'Stone Town Tour (City Walk)',
    slug: 'stone-town-tour',
    duration: 'Half Day',
    category: 'City & Cultural',
    tagline: 'Explore the UNESCO World Heritage streets, Sultan palaces & spice markets',
    description:
      'Immerse yourself in centuries of Swahili, Arabic, Persian, and European history. Walk through the narrow winding alleys of Stone Town, see the House of Wonders, the Old Fort, the former Slave Market site, and bustling local bazaars with your private licensed guide.',
    pricing: {
      single: 120,
      couple: 160,
      group5to10: 40,
    },
    inclusions: [
      'Museum entrance tickets',
      'Hotel transfer (Stone Town area)',
      'Professional licensed local guide',
      '1 soft drink & mineral water per person',
    ],
    highlights: [
      'Historic UNESCO World Heritage alleys',
      'Former Slave Market & Anglican Cathedral',
      'Freddie Mercury birthplace & House of Wonders',
      'Authentic Darajani spice and fruit market',
    ],
    image: '/images/tours/Stonetown/ZOM_0097.JPG-300kb.jpg',
    featured: false,
  },
  {
    id: 'tour-2',
    title: 'Prison Island (Giant Tortoises)',
    slug: 'prison-island',
    duration: 'Half Day',
    category: 'City & Cultural',
    tagline: 'Visit Changuu Island and feed the majestic 100+ year old Aldabra Giant Tortoises',
    description:
      'Take a scenic 30-minute wooden boat ride across azure waters to Prison Island. Discover the historical quarantine station built in 1893 and spend quality time feeding and interacting with giant Aldabra tortoises, some older than 150 years.',
    pricing: {
      single: 155,
      couple: 190,
      group5to10: 94,
    },
    inclusions: [
      'Marine conservation fees',
      'Island entrance ticket',
      'Private traditional wooden boat ride',
      'Roundtrip hotel transfers',
      'Professional private guide',
      'Soft drink & mineral water',
    ],
    highlights: [
      'Aldabra giant tortoises interaction & feeding',
      'Historical 1893 prison & quarantine ruins',
      'Crystal-clear turquoise coastal waters',
      'Panoramic ocean views back to Stone Town',
    ],
    image: '/images/tours/Prison/PXL_20260819_103528045.MP.jpg-200kb.jpg',
    featured: false,
  },
  {
    id: 'tour-3',
    title: 'Nakupenda White Sandbank',
    slug: 'nakupenda-sandbank',
    duration: 'Half Day',
    category: 'Sea & Water',
    tagline: 'Sunbathe and snorkel on a disappearing pure white sandbank in the Indian Ocean',
    description:
      'Sail out to the famous Nakupenda ("I Love You") sandbank. Bask in the sun, swim in crystalline warm waters, snorkel over vibrant coral gardens, and savor fresh tropical fruits and light snacks served right on the beach.',
    pricing: {
      single: 175,
      couple: 210,
      group5to10: 97,
    },
    inclusions: [
      'Marine conservation fees',
      'Private boat charter',
      'Hotel pickup and drop-off',
      'Fresh tropical fruits, snacks & soft drinks',
      'Professional guide & snorkeling gear',
    ],
    highlights: [
      'Pristine white sandbank emerging at low tide',
      'World-class snorkeling among colorful reef fish',
      'Fresh mangoes, pineapples, watermelon & coconuts',
      'Private sun tent shade setup',
    ],
    image: '/images/tours/Nakupenda/Nakupenda-Island-Zan-The-Level-2.jpg.jpeg',
    featured: false,
  },
  {
    id: 'tour-4',
    title: 'Town Full Day Combo (Stone Town + Prison + Sandbank)',
    slug: 'town-full-day-combo',
    duration: 'Full Day',
    category: 'Full Day Combos',
    tagline: 'The ultimate 3-in-1 Zanzibar highlight: Heritage, tortoises & tropical sandbank',
    description:
      'The comprehensive Zanzibar day trip! Start with a guided historic walk through Stone Town, cruise to Prison Island to feed the giant tortoises, and end the afternoon unwinding on the breathtaking Nakupenda Sandbank with an abundant seafood lunch.',
    pricing: {
      single: 190,
      couple: 230,
      group5to10: 100,
      group20: 60,
    },
    inclusions: [
      'Stone Town museum & historical site fees',
      'Prison Island entry ticket',
      'Marine conservation fees',
      'Private dhow boat charter',
      'Roundtrip hotel transfers',
      'Fresh seafood lunch & tropical fruit platter',
      'Professional English/Italian/Swahili guide',
      'Soft drinks & bottled water throughout',
    ],
    highlights: [
      'All 3 top attractions in one seamless day',
      'Grilled seafood feast (lobster, calamari, fish)',
      'Rich culture + exotic wildlife + ocean relaxation',
      'All transfer logistics taken care of by Ibrahim',
    ],
    image: '/images/tours/Stonetown/ZOM_0097.JPG-300kb.jpg',
    featured: true,
  },
  {
    id: 'tour-5',
    title: 'Mnemba Island (Swim with Dolphins)',
    slug: 'mnemba-island',
    duration: 'Full Day',
    category: 'Sea & Water',
    tagline: 'Snorkel the premier coral reef atoll & spot playful wild dolphins',
    description:
      'Cruise to the marine conservation sanctuary of Mnemba Atoll. Experience prime snorkeling with tropical fish species, stingrays, and sea turtles, with a high chance of spotting and swimming alongside wild dolphins in their natural habitat.',
    pricing: {
      single: 158,
      couple: 182,
      group5to10: 83,
    },
    inclusions: [
      'Marine conservation & park fees',
      'Private speedboat transfer to Mnemba Reef',
      'Hotel pickup & drop-off',
      'Fresh tropical fruits & chilled soft drinks',
      'Professional guide & snorkeling gear',
    ],
    highlights: [
      'Premier coral reef snorkeling spot in East Africa',
      'Wild dolphin spotting in Muyuni / Matemwe Bay',
      'Crystal clear 20+ meter visibility waters',
      'Fresh coconut water & sweet seasonal fruits',
    ],
    image: '/images/tours/Mnemba/Mnemba-Island-4.jpg.jpeg',
    featured: true,
  },
  {
    id: 'tour-6',
    title: 'Spice Tour',
    slug: 'spice-tour',
    duration: 'Half Day',
    category: 'City & Cultural',
    tagline: 'Smell, touch and taste cloves, vanilla, nutmeg & cinnamon in their organic habitat',
    description:
      'Discover why Zanzibar is known as the "Spice Island." Walk through lush tropical spice plantations, witness how local farmers harvest spices, taste exotic fruits, and receive a handmade palm leaf hat and necklace.',
    pricing: {
      single: 105,
      couple: 120,
      group5to10: 50,
    },
    inclusions: [
      'Organic spice farm entrance fee',
      'Roundtrip hotel transfer',
      'Expert local spice botanist guide',
      'Fresh exotic fruit tasting & 1 soft drink',
    ],
    highlights: [
      'Smell and taste raw cloves, cardamom, black pepper & vanilla',
      'Coconut tree climbing performance ("Butterfly Man")',
      'Traditional palm leaf crafts & crown gifts',
      'Opportunity to purchase fresh farm spices directly',
    ],
    image: '/images/tours/SpiceFarm/2X7A7374.jpg-100kb.jpg',
    featured: false,
  },
  {
    id: 'tour-7',
    title: 'Dhow Sunset Cruise',
    slug: 'dhow-sunset-cruise',
    duration: 'Half Day',
    category: 'Sea & Water',
    tagline: 'Sail into the glowing Zanzibar sunset on an authentic handcrafted wooden dhow',
    description:
      'Step aboard a traditional Swahili dhow as the late afternoon breeze picks up. Glide along the coast of Stone Town or Kendwa, listening to gentle acoustic Swahili rhythms while sipping drinks and watching the sky turn brilliant gold and crimson.',
    pricing: {
      single: 120,
      couple: 150,
      group5to10: 62,
    },
    inclusions: [
      'Traditional wooden dhow cruise',
      'Soft drinks, chilled juices & tropical fruit platter',
      'Roundtrip hotel transfer',
      'Experienced captain & local guide',
    ],
    highlights: [
      'Breathtaking Indian Ocean sunset panorama',
      'Authentic handcrafted wooden sailing vessel',
      'Relaxing Swahili coastal atmosphere',
      'Ideal for couples, honeymooners and families',
    ],
    image: '/images/tours/Sunset/Zanzibar_Dhow_Sunset_Cruise_03.jpg.jpeg',
    featured: false,
  },
  {
    id: 'tour-8',
    title: 'North Full Day Combo (Mnemba + Spice + Dhow Sunset)',
    slug: 'north-full-day-combo',
    duration: 'Full Day',
    category: 'Full Day Combos',
    tagline: 'The complete North Zanzibar package: Dolphins, aromatic spices & golden sunset cruise',
    description:
      'A full day of tropical adventure in northern Zanzibar. Morning snorkeling at Mnemba Atoll with dolphins, midday journey through the aromatic spice plantations, and ending with a serene wooden dhow sunset cruise along the coastline.',
    pricing: {
      single: 190,
      couple: 230,
      group5to10: 100,
      group20: 70,
    },
    inclusions: [
      'Marine conservation fees & Mnemba boat',
      'Spice farm entrance fee & guided tour',
      'Evening dhow sunset cruise',
      'All roundtrip hotel transfers in private AC vehicle',
      'Tropical fruits, refreshments & soft drinks',
      'Full-day private guide with Ibrahim',
    ],
    highlights: [
      'Mnemba dolphin swim & coral reef snorkeling',
      'Hands-on spice tour with exotic fruit tastings',
      'Romantic dhow sunset sail on the ocean',
      'Maximum value multi-destination full-day itinerary',
    ],
    image: '/images/tours/Sunset/Zanzibar_Dhow_Sunset_Cruise_03.jpg.jpeg',
    featured: false,
  },
  {
    id: 'tour-9',
    title: 'Jozani Forest (Red Colobus Monkeys)',
    slug: 'jozani-forest',
    duration: 'Half Day',
    category: 'Nature & Wildlife',
    tagline: 'Meet the endangered Zanzibar Red Colobus Monkeys in their native sanctuary',
    description:
      'Venture into Zanzibar’s only national park, Jozani Chwaka Bay. Get up-close views of the playful and habituated Red Colobus monkeys found nowhere else on earth, explore mahogany forest trails, and stroll along the mangrove boardwalk.',
    pricing: {
      single: 122,
      couple: 144,
      group5to10: 54,
    },
    inclusions: [
      'Jozani National Park entry fees & conservation levy',
      'Roundtrip hotel transfer',
      'Official park ranger & private tour guide',
      '1 soft drink & bottled water',
    ],
    highlights: [
      'Endangered endemic Zanzibar Red Colobus monkeys',
      'Ancient mahogany and eucalyptus trees',
      'Elevated mangrove swamp boardwalk',
      'Rich birdlife, medicinal plants and butterflies',
    ],
    image: '/images/tours/Jozani/6803148a-2b22-4f22-be2f-0825a2159110.jpg.jpeg',
    featured: false,
  },
  {
    id: 'tour-10',
    title: 'Salaam Cave (Swim with Sea Turtles)',
    slug: 'salaam-cave',
    duration: 'Half Day',
    category: 'Nature & Wildlife',
    tagline: 'Swim alongside and feed rescued green sea turtles in a natural coral cave aquarium',
    description:
      'Visit the natural tidal pool of Salaam Cave (or Baraka Aquarium). Step into the clear sea water to hand-feed seaweed to gentle rescued green sea turtles and swim alongside these peaceful ancient marine creatures.',
    pricing: {
      single: 122,
      couple: 144,
      group5to10: 74,
    },
    inclusions: [
      'Salaam Cave conservation entrance fee',
      'Roundtrip hotel transfer',
      'Private guide & turtle feeding seaweed',
      '1 soft drink & bottled water',
    ],
    highlights: [
      'Direct swimming with rescued sea turtles',
      'Hand-feeding seaweed to friendly green turtles',
      'Unique natural coral stone tidal lagoon',
      'Educational conservation talk by local caretakers',
    ],
    image: '/images/tours/Salam_Cave/038e96383d328557908a6b117db3326a876263affc1f3340270b8eae1a27f946.jpg.jpeg',
    featured: false,
  },
  {
    id: 'tour-11',
    title: 'The Rock Restaurant',
    slug: 'the-rock-restaurant',
    duration: 'Half Day',
    category: 'Island Experiences',
    tagline: 'Visit the world-renowned dining landmark perched on a coral outcrop in Michamvi',
    description:
      'Enjoy seamless private transportation to the iconic The Rock Restaurant at Michamvi Pingwe. At high tide, take a short wooden boat ride to the rock; at low tide, walk right across the exposed reef sands.',
    pricing: {
      single: 97,
      couple: 105,
      group5to10: 35,
    },
    inclusions: [
      'Private roundtrip hotel transfer to Michamvi',
      'Table booking coordination assistance',
      'Professional driver / local escort',
    ],
    highlights: [
      'Zanzibar’s most photographed landmark restaurant',
      'Panoramic 360-degree ocean views from the terrace',
      'Combine with relaxation on gorgeous Michamvi beach',
      'Stress-free roundtrip private transfer',
    ],
    image: '/images/tours/Rock_Restaurant/The-rock-zanzibar-aerial-view.webp',
    featured: true,
  },
  {
    id: 'tour-12',
    title: 'South Full Day Combo (Jozani + Salaam + The Rock)',
    slug: 'south-full-day-combo',
    duration: 'Full Day',
    category: 'Full Day Combos',
    tagline: 'Red colobus monkeys, sea turtle swimming, and dinner at The Rock Restaurant',
    description:
      'The definitive South & East coast exploration! Start the morning with the monkeys of Jozani Forest, swim with the rescued sea turtles at Salaam Cave, and spend the afternoon and sunset at Michamvi beach and The Rock Restaurant.',
    pricing: {
      single: 150,
      couple: 200,
      group5to10: 80,
      group20: 60,
    },
    inclusions: [
      'Jozani National Park entrance fee',
      'Salaam Cave entrance fee & turtle feeding',
      'Michamvi / The Rock Restaurant transfer',
      'Roundtrip hotel transfers in private AC vehicle',
      'Professional guide with Ibrahim',
      'Soft drinks & mineral water',
    ],
    highlights: [
      'Wildlife encounters: monkeys and sea turtles',
      'Visit the world-famous Rock Restaurant in Michamvi',
      'Private, comfortable, air-conditioned vehicle all day',
      'Customizable pacing for family or romantic couples',
    ],
    image: '/images/tours/Rock_Restaurant/The-rock-zanzibar-aerial-view.webp',
    featured: false,
  },
  {
    id: 'tour-13',
    title: 'Safari Blue (Snorkeling)',
    slug: 'safari-blue',
    duration: 'Full Day',
    category: 'Sea & Water',
    tagline: 'Zanzibar’s #1 full-day ocean adventure with dhow sailing & lavish seafood feast',
    description:
      'Departing from Fumba in Menai Bay Conservation Area, Safari Blue takes you on handcrafted wooden dhows to isolated sandbanks, prime snorkeling reefs, a hidden mangrove lagoon for swimming, and a desert island for a legendary grilled seafood lunch.',
    pricing: {
      single: 200,
      couple: 230,
      group5to10: 77,
      group20: 60,
    },
    inclusions: [
      'Menai Bay marine conservation fees',
      'Handcrafted traditional sailing dhow charter',
      'Roundtrip hotel transfers',
      'Lavish seafood buffet (lobster, slipper lobster, fish, calamari)',
      'Exotic fruit tasting with 10+ tropical fruits',
      'Professional guides, snorkeling gear & life vests',
      'Soft drinks, mineral water & fresh juice',
    ],
    highlights: [
      'Zanzibar’s most famous and acclaimed ocean excursion',
      'Spectacular sandbank lounging & reef snorkeling',
      'Mangrove lagoon natural swimming pool',
      'Giant 500-year-old baobab tree climb on Kwale Island',
    ],
    image: '/images/tours/Safariblue/the-original-safari-blue.jpg.jpeg',
    featured: true,
  },
  {
    id: 'tour-14',
    title: 'Village Tour (Culture + Cooking Class)',
    slug: 'village-tour-cooking-class',
    duration: 'Full Day',
    category: 'City & Cultural',
    tagline: 'Step into authentic Swahili village life and master traditional island recipes',
    description:
      'Experience genuine Zanzibari hospitality away from the typical tourist routes. Walk through a traditional village, learn how locals weave palm roofs, grind cassava, and participate in a step-by-step Swahili cooking class using fresh farm ingredients and coconut milk.',
    pricing: {
      single: 160,
      couple: 185,
      group5to10: 72,
      group20: 50,
    },
    inclusions: [
      'Roundtrip private hotel transfer',
      'Professional local cultural guide',
      'Hands-on Swahili cooking masterclass',
      'Full multi-course lunch prepared in class',
      'Village community contribution & market visit',
      'Soft drinks & fresh coconut water',
    ],
    highlights: [
      'Genuine connection with local village families',
      'Learn Swahili cooking techniques (Pilau, Coconut Curry, Chapati)',
      'Support community-based sustainable tourism',
      'Take home authentic recipe secrets from Zanzibar',
    ],
    image: '/images/tours/Village/Look-like-locals.jpg.jpeg',
    featured: false,
  },
];

export const TRANSFER_ROUTES: TransferRoute[] = [
  // Airport <-> Stone Town
  {
    id: 'trans-1',
    origin: 'Zanzibar Airport (ZNZ)',
    destination: 'Stone Town',
    distanceKm: 10,
    durationEstimate: '20–30 min',
    pricing: {
      van1to3: 20,
      van4to6: 25,
      miniBus7to12: 35,
      bigBus13to25: 50,
    },
  },
  {
    id: 'trans-2',
    origin: 'Stone Town',
    destination: 'Zanzibar Airport (ZNZ)',
    distanceKm: 10,
    durationEstimate: '20–30 min',
    pricing: {
      van1to3: 20,
      van4to6: 25,
      miniBus7to12: 35,
      bigBus13to25: 50,
    },
  },

  // Stone Town <-> Nungwi / Kendwa
  {
    id: 'trans-3',
    origin: 'Stone Town',
    destination: 'Nungwi / Kendwa',
    distanceKm: 55,
    durationEstimate: '1–1.5 h',
    pricing: {
      van1to3: 40,
      van4to6: 45,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },
  {
    id: 'trans-4',
    origin: 'Nungwi / Kendwa',
    destination: 'Stone Town',
    distanceKm: 55,
    durationEstimate: '1–1.5 h',
    pricing: {
      van1to3: 40,
      van4to6: 45,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },

  // Stone Town <-> Paje / Jambiani
  {
    id: 'trans-5',
    origin: 'Stone Town',
    destination: 'Paje / Jambiani',
    distanceKm: 50,
    durationEstimate: '1–1.5 h',
    pricing: {
      van1to3: 40,
      van4to6: 45,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },
  {
    id: 'trans-6',
    origin: 'Paje / Jambiani',
    destination: 'Stone Town',
    distanceKm: 50,
    durationEstimate: '1–1.5 h',
    pricing: {
      van1to3: 40,
      van4to6: 45,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },

  // Paje / Jambiani <-> Nungwi / Kendwa
  {
    id: 'trans-7',
    origin: 'Paje / Jambiani',
    destination: 'Nungwi / Kendwa',
    distanceKm: 70,
    durationEstimate: '1.5–2 h',
    pricing: {
      van1to3: 50,
      van4to6: 60,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },
  {
    id: 'trans-8',
    origin: 'Nungwi / Kendwa',
    destination: 'Paje / Jambiani',
    distanceKm: 70,
    durationEstimate: '1.5–2 h',
    pricing: {
      van1to3: 50,
      van4to6: 60,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },

  // Airport <-> Paje / Jambiani
  {
    id: 'trans-9',
    origin: 'Zanzibar Airport (ZNZ)',
    destination: 'Paje / Jambiani',
    distanceKm: 50,
    durationEstimate: '1–1.5 h',
    pricing: {
      van1to3: 50,
      van4to6: 60,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },
  {
    id: 'trans-10',
    origin: 'Paje / Jambiani',
    destination: 'Zanzibar Airport (ZNZ)',
    distanceKm: 50,
    durationEstimate: '1–1.5 h',
    pricing: {
      van1to3: 50,
      van4to6: 60,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },

  // Airport <-> Nungwi / Kendwa
  {
    id: 'trans-11',
    origin: 'Zanzibar Airport (ZNZ)',
    destination: 'Nungwi / Kendwa',
    distanceKm: 65,
    durationEstimate: '1.5 h',
    pricing: {
      van1to3: 50,
      van4to6: 60,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },
  {
    id: 'trans-12',
    origin: 'Nungwi / Kendwa',
    destination: 'Zanzibar Airport (ZNZ)',
    distanceKm: 65,
    durationEstimate: '1.5 h',
    pricing: {
      van1to3: 50,
      van4to6: 60,
      miniBus7to12: 75,
      bigBus13to25: 100,
    },
  },
];

export const VEHICLES: Vehicle[] = [
  {
    id: 'veh-van',
    name: 'Private Tourist Van',
    capacity: '1–6 passengers',
    features: [
      'Full Air Conditioning (A/C)',
      'Professional licensed English/Italian-speaking driver',
      'Spacious luggage boot for up to 6 large suitcases',
      'Clean, comfortable high-roof seating',
      'Bottled mineral water included',
    ],
    image: '/images/van.webp',
  },
  {
    id: 'veh-minibus',
    name: 'Executive Mini Bus',
    capacity: '7–12 passengers',
    features: [
      'High-power Dual A/C system',
      'Experienced commercial tourism chauffeur',
      'Ample luggage compartment + roof rack option',
      'Reclining passenger seats with seatbelts',
      'Ideal for medium family and friends groups',
    ],
    image: '/images/minibus.webp',
  },
  {
    id: 'veh-bigbus',
    name: 'Luxury Coach / Big Bus',
    capacity: '13–25 passengers',
    features: [
      'Heavy-duty climate control climate cabin',
      'Professional driver + tour assistant on board',
      'Maximum luggage capacity for large tour groups',
      'Public address (PA) microphone system for guides',
      'Smooth suspension for island-wide transfers',
    ],
    image: '/images/bigbus.webp',
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Sarah & James Jenkins',
    country: 'United Kingdom',
    rating: 5,
    tourTitle: 'Safari Blue & Stone Town Full Day',
    content:
      'Booking with Ibrahim made our Zanzibar holiday seamless and unforgettable! He met us on time with a clean AC van, shared amazing stories about Stone Town, and the Safari Blue seafood lunch was simply out of this world. Booking through WhatsApp was instant and stress-free.',
    date: 'February 2026',
  },
  {
    id: 'rev-2',
    author: 'Marco Rossi & Famiglia',
    country: 'Italy',
    rating: 5,
    tourTitle: 'Mnemba Island & Spice Tour',
    content:
      'Ibrahim parla un ottimo italiano ed è stato una guida fantastica per tutta la nostra famiglia! Abbiamo nuotato con i delfini a Mnemba e visitato le piantagioni di spezie. Prezzi chiarissimi, nessun costo nascosto e puntualità svizzera. Consigliatissimo a tutti gli italiani!',
    date: 'January 2026',
  },
  {
    id: 'rev-3',
    author: 'Astrid & Johan Lindqvist',
    country: 'Sweden',
    rating: 5,
    tourTitle: 'Airport Transfers & Jozani Forest',
    content:
      'We booked both airport transfers and the Jozani Forest tour with Ibrahim. Communication on WhatsApp was super quick, driver was waiting right at the arrivals terminal with a name sign, and seeing the Red Colobus monkeys was magical. 10/10 service!',
    date: 'December 2025',
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'Do I pay online when submitting a booking request?',
    answer:
      'No, there is NO online payment required on this website. When you submit a booking request or message Ibrahim on WhatsApp, your dates and details are reviewed and confirmed manually. Payment is made off-platform in person (Cash in USD, EUR, GBP, or TZS, M-Pesa, or direct bank transfer) upon meeting your guide/driver.',
    category: 'Booking & Payment',
  },
  {
    id: 'faq-2',
    question: 'How is my booking confirmed?',
    answer:
      'Once you submit a request form or send a WhatsApp message, Ibrahim personally verifies availability and responds within a short time with full pickup details, vehicle assignment, and your final voucher confirmation.',
    category: 'Booking & Payment',
  },
  {
    id: 'faq-3',
    question: 'Can I book directly via WhatsApp?',
    answer:
      'Yes, absolutely! WhatsApp is the fastest and most convenient method. You can click any of our "Chat on WhatsApp" buttons with prefilled tour or transfer details, and Ibrahim will assist you immediately in English, Italian, or Swahili.',
    category: 'Booking & Payment',
  },
  {
    id: 'faq-4',
    question: 'What payment methods do you accept?',
    answer:
      'We accept Cash (US Dollars printed after 2009, Euros, British Pounds, and Tanzanian Shillings), Vodacom M-Pesa mobile money, and local/international bank transfers.',
    category: 'Payment',
  },
  {
    id: 'faq-5',
    question: 'Are airport pickups and hotel transfers private?',
    answer:
      'Yes, 100% of our transfers and tours are private for you and your group. Your driver will greet you at Abeid Amani Karume International Airport (ZNZ) arrivals with a personalized name board and assist with your luggage.',
    category: 'Transfers',
  },
  {
    id: 'faq-6',
    question: 'Can I customize a tour or combine multiple destinations?',
    answer:
      'Yes! Because Ibrahim is a private operator, we can tailor custom combos to suit your schedule and interests (e.g. combining Jozani Forest, Spice Farm, and The Rock Restaurant in a single day). Simply let us know your preferred itinerary on WhatsApp.',
    category: 'Tours',
  },
  {
    id: 'faq-7',
    question: 'What happens after I submit a booking request on the site?',
    answer:
      'We receive your details immediately. Ibrahim checks driver and boat availability for your requested date and contacts you directly via WhatsApp or Email to confirm meeting time, hotel pickup location, and final pricing.',
    category: 'Booking & Payment',
  },
];
